const jobs = [
  { title: "Cloud Support Engineer", company: "Northstar Systems", location: "Birmingham · Hybrid", salary: "£42k–£48k", score: 88, recommendation: "APPLY", skills: ["Azure", "Microsoft 365", "Entra ID"] },
  { title: "Infrastructure Engineer", company: "Orbit Events", location: "Remote · UK", salary: "£40k–£45k", score: 79, recommendation: "APPLY", skills: ["Windows Server", "VMware", "Networking"] },
  { title: "Senior IT Support Engineer", company: "Coventry Digital", location: "Coventry · Onsite", salary: "£35k–£39k", score: 66, recommendation: "CONSIDER", skills: ["Intune", "Azure", "IT Support"] },
];

export default function Home() {
  return <main className="main"><div className="top"><div><span className="eyebrow">Personal recruitment intelligence</span><h1>Good evening, Derek.</h1><p>Here are the strongest career moves found for you.</p></div><button className="button">Run job search</button></div><section className="metrics"><div className="card metric"><span>New matches</span><strong>18</strong><small className="apply">+6 today</small></div><div className="card metric"><span>Recommended</span><strong>7</strong><small>Score 75+</small></div><div className="card metric"><span>Applications</span><strong>4</strong><small>2 awaiting reply</small></div><div className="card metric"><span>Interviews</span><strong>1</strong><small className="apply">Next Thursday</small></div></section><div className="grid"><section className="card"><div className="top"><div><h2>Best matches</h2><p>Ranked by skills, progression, pay and travel.</p></div><a className="eyebrow" href="/jobs">View all →</a></div><div className="jobs">{jobs.map((job) => <article className="card job" key={job.title}><div><div className={job.recommendation.toLowerCase()}>{job.recommendation}</div><h3>{job.title}</h3><p>{job.company}</p><div className="meta"><span className="pill">{job.location}</span><span className="pill">{job.salary}</span></div><div className="skills">{job.skills.map((skill) => <span className="pill" key={skill}>{skill}</span>)}</div></div><div className="score">{job.score}</div></article>)}</div></section><aside className="jobs"><section className="card"><span className="eyebrow">Weekly target</span><h2>4 of 6 quality applications</h2><div className="bar"><span style={{ width: "67%" }} /></div><p>Two more strong applications keeps you on plan.</p></section><section className="card"><span className="eyebrow">Skill signal</span><h2>Azure is opening doors</h2><p>Roles mentioning Azure and Entra ID are scoring 14 points higher for your profile.</p></section><section className="card"><span className="eyebrow">Agent decision</span><h2>Prioritise cloud-facing roles</h2><p>Your onsite leadership plus Microsoft stack is strongest for Cloud Support and Infrastructure Engineer roles above £38k.</p></section></aside></div></main>;
}
